# ----------------------------------------------------------------------- #
# RUNTIME LIMITATION                                                      #
# ----------------------------------------------------------------------- #

# Maximum expected execution time for the job, in seconds
# 43200 = 12h
# 86400 = 24h
MaxTime = 43200

# Kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

# ----------------------------------------------------------------------- #
# RESSOURCE SELECTION                                                     #
# ----------------------------------------------------------------------- #

request_memory = 6144
request_cpus = 1

# ----------------------------------------------------------------------- #
# FOLDER SELECTION                                                        #
# ----------------------------------------------------------------------- #

environment = "PYTHONUNBUFFERED=TRUE"
executable = /home/mrateike/miniconda3/envs/fairlearn_original/bin/python

error = None/Uncalibrated/error/experiment.$(Process).err
output = None/Uncalibrated/output/experiment.$(Process).out
log = None/Uncalibrated/log/experiment.$(Process).log
# ----------------------------------------------------------------------- #
# QUEUE                                                                   #
# ----------------------------------------------------------------------- #

arguments = run.py -T1 5000 -T2 50000 -TT10000 -fDP -bt none-eps 0.01 -nu 1e-06 -d UncalibratedNone/Uncalibrated/results  
queue 
arguments = run.py -T1 10000 -T2 50000 -TT10000 -fDP -bt none-eps 0.01 -nu 1e-06 -d UncalibratedNone/Uncalibrated/results  
queue 
arguments = run.py -T1 15000 -T2 50000 -TT10000 -fDP -bt none-eps 0.01 -nu 1e-06 -d UncalibratedNone/Uncalibrated/results  
queue 
