# ----------------------------------------------------------------------- #
# RUNTIME LIMITATION                                                      #
# ----------------------------------------------------------------------- #

# Maximum expected execution time for the job, in seconds
# 43200 = 12h
# 86400 = 24h
MaxTime = 43200

# Kill the jobs without warning
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))

# ----------------------------------------------------------------------- #
# RESSOURCE SELECTION                                                     #
# ----------------------------------------------------------------------- #

request_memory = 6144
request_cpus = 1

# ----------------------------------------------------------------------- #
# FOLDER SELECTION                                                        #
# ----------------------------------------------------------------------- #

environment = "PYTHONUNBUFFERED=TRUE"
executable = /home/mrateike/miniconda3/envs/fairlearn_original/bin/python

error = /Users/mrateike/PycharmProjects/fair_minimonster/results/2020-06-11-15-08-11_Oracle_Uncalibrated_DP/error/experiment.$(Process).err
output = /Users/mrateike/PycharmProjects/fair_minimonster/results/2020-06-11-15-08-11_Oracle_Uncalibrated_DP/output/experiment.$(Process).out
log = /Users/mrateike/PycharmProjects/fair_minimonster/results/2020-06-11-15-08-11_Oracle_Uncalibrated_DP/log/experiment.$(Process).log
# ----------------------------------------------------------------------- #
# QUEUE                                                                   #
# ----------------------------------------------------------------------- #

arguments = exp/main_expg.py -T1 69 -T2 4731 -TT 1200 -f DP -eps 0.01 -nu 1e-06   
queue 
